mes = int(input('Entre um valor na faixa de 1 a 12: '))
if(mes == 1):    print('Corresponde a Janeiro')
elif(mes ==  2): print('Corresponde a Fevereiro')
elif(mes ==  3): print('Corresponde a Março')
elif(mes ==  4): print('Corresponde a Abril')
elif(mes ==  5): print('Corresponde a Maio')
elif(mes ==  6): print('Corresponde a Junho')
elif(mes ==  7): print('Corresponde a Julho')
elif(mes ==  8): print('Corresponde a Agosto')
elif(mes ==  9): print('Corresponde a Setembro')
elif(mes == 10): print('Corresponde a Outubro')
elif(mes == 11): print('Corresponde a Novembro')
elif(mes == 12): print('Corresponde a Dezembro')
else: print('Entrada inválida')
input()
